title: "Minghao Li / 李明昊"
description: "Academic Homepage / 学术主页"
baseurl: ""
url: "https://Minghao-Li-25.github.io"
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag
defaults:
  - scope:
      path: ""
    values:
      layout: "single"
