title: "Minghao Li / 李明昊"
description: "Academic Homepage / 学术主页"
baseurl: ""
url: "https://yourusername.github.io"
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
defaults:
  - scope:
      path: ""
    values:
      layout: "single"
